### ISSUE TITLE
Minimize Mapbox freehand imports when zooming out

### ISSUE THREAD

**Issue by LukeSwart** [smartercleanup/duwamish#45]
When we zoom out, we can minimize the Shareabouts markers, but not the Mapbox import markers because that layer is not listening to the "zoomend" events.

**Comment by geodesy99** [comment]
This feature relates to the design intent of the various cartographic stacks. All have compromises in order to do other things well. Usually, if you are encountering some limitation to Mapbox ( or other ), it is already implemented in one of the other stacks, in this case, Geoserver, and specifically the use of the SLD ( Styled Layer Descriptor ) file. 
From the [GeoServer 2.6.x User Manual » Styling » Introduction to SLD](http://docs.geoserver.org/stable/en/user/styling/sld-introduction.html) Within the top-level style are one or more feature type styles, which act as “virtual layers” to provide control over rendering order (allowing styling effects such as cased lines for roads). 'Each feature type style contains one or more rules, which control how styling is applied based on feature attributes and **zoom level**'. 
To some extent Mapbox's Tilemill CartoCSS already supports zoom related styling - See [Advanced Map Design](https://www.mapbox.com/tilemill/docs/guides/advanced-map-design/#advanced_map_design) - but read though to the end. While creating, iterating the design, and then deploying the symbology in a high end GIS system like QGIS or ArcGIS is non-trivial, IMHO, unless it is very simple, it is really complex to create, read, and maintain in Tilemill. 
( it's not clear to me whether the difficulty might be caused by some event not being passed between the API's ... does the zoomend work correctly outside the Shareabouts integration ).

**Comment by LukeSwart** [comment]
I think this can be implemented in Javascript in the same way that the Shareabouts (or 'Reports') layer is adjustable based on the zoom level. If you try zooming on the map on the demo, I believe the Shareabouts layer resizes at zoom levels 11 and 13. I think would need to implement a listener, similar to the one on the Shareabout layer, that refreshes the layer when the zoom level is changed.

**Comment by futuresoup** [comment]
Hopefully this can be coded when resolving Issue #174

**Comment by LukeSwart** [comment]
Yep, this was completed when resolving #174 :-D
